
export const localImages = {
  logo: "/images/logo.jpeg",
  hero: "/images/yosai-hero.jpeg",
  monocromatico: "/images/yosai-monocromatico.png",
  yosai1: "/images/yosai1.jpeg",
  plataforma: "/images/yosaiplataforma-sinfondo.webp",
  redes: "/images/yosairedes-sinfondo.webp",
};

export const icons = {
  apple: "/icons/apple.png",
  contacto: "/icons/contacto.png",
  facebook: "/icons/facebook.png",
  instagram: "/icons/instagram.png",
  instagramAlt: "/icons/Instagram_icon.png",
  spotify: "/icons/spotify.png",
  youtube: "/icons/youtube.png",
};

export const videos = {
  animation: "/images/yosai-animation.mp4",
  animacion2: "/images/yosaianimacion2.mp4",
  video: "/images/yosaivideo.mp4",
};

export const images = [
    {id: 1,     image: "yosai elegante",                                src: "https://res.cloudinary.com/dlw6fupap/image/upload/f_auto,q_auto/mixboard-image_4_iecjmq",                     description: ""},
    {id: 2,     image: "El Legado",                                     src: "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776696162/mixboard-image_3_fz7tc3.png",     description: "[URL_FOTO_YOSAI] Full shot of Yosai walking in the center of a grand minimalist mansion hall at night, symmetrical composition, floor-to-ceiling windows, holding a glass of red wine, wearing a black silk suit, camera at low angle, cinematic architectural lighting with burgundy (#82000f) accents, shot on ARRI Alexa Mini LF, 25mm lens, wide perspective, high-end lifestyle, 8k --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 3,     image: "El Backstage",                                  src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776698455/mixboard-image_11_sfbyy6.png",   description : "[URL_FOTO_YOSAI] Mirror reflection shot of Yosai in a dark dressing room, getting ready, identical facial features, warm vanity lights mixed with burgundy (#82000f) backlighting, moody atmosphere, cinematic storytelling, shot on Hasselblad X2D, 55mm lens, medium close-up, high dynamic range, intimate moment, realistic textures --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 4,     image: "El Detalle",                                    src: "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776699087/mixboard-image_9_plgsgq.png",     description: "Extreme macro shot of Yosai's jawline and neck, focus on a high-end diamond pendant with YOSAI typography, burgundy (#82000f) light reflecting off diamonds, sharp skin texture, subtle sweat, dark moody background, shot on Canon EOS R3, 100mm Macro lens, shallow depth of field, cinematic sparkle, 8k --cref [URL_FOTO_YOSAI] --cw 80 --ar 16:9"},
    {id: 5,     image: "El Origen (Calle y Estilo)",                    src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776696047/mixboard-image_4_iecjmq.png",    description: "- [URL_FOTO_YOSAI] American shot of Yosai leaning on a rooftop railing, city skyline bokeh in the background, night scene, wearing a long burgundy velvet trench coat, urban fashion style, identical face preservation, neon burgundy light reflection on wet floor, shot on Nikon Z9, 35mm lens, gritty but high-end urban aesthetic, volumetric city lights, 8k resolution --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 6,     image: "El Éxito (Lujo y Sofisticación)",               src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776777583/mixboard-image_2_tbcm0f.png",    description: "[URL_FOTO_YOSAI] Medium shot of Yosai relaxing inside a luxury private jet cabin, identical facial features in profile, looking out the window, interior lighting is dark with burgundy (#82000f) LED accents, premium black leather textures, luxury watch on wrist, shot on Phase One XF, 35mm lens, moody and expensive atmosphere, clean composition, hyper-realistic --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 7,     image: "ZoomParallax (La Vida en Movimiento)",          src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776777974/mixboard-image_3_ghmi9e.png",    description: "[URL_FOTO_YOSAI] Dynamic action shot of Yosai walking through a luxury black marble corridor, identical facial features from side profile, camera at waist height pointing upwards, wide-angle perspective, wearing high-end techwear with burgundy accents, neon burgundy (#82000f) linear lights reflecting on marble, motion blur on background elements, shot on Leica M11-P, 35mm Summilux lens, harsh cinematic flash mixed with ambient red light, grainy reportage style, sharp focus on the artist's face, 8k resolution --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 8,     image: "ZoomParallax (La Vida en Movimiento) 2",        src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776778016/mixboard-image_1_qhsybr.png",    description: "- [URL_FOTO_YOSAI] Dynamic action shot of Yosai walking through a luxury black marble corridor, identical facial features from side profile, camera at waist height pointing upwards, wide-angle perspective, wearing high-end techwear with burgundy accents, neon burgundy (#82000f) linear lights reflecting on marble, motion blur on background elements, shot on Leica M11-P, 35mm Summilux lens, harsh cinematic flash mixed with ambient red light, grainy reportage style, sharp focus on the artist's face, 8k resolution --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 9,     image: "ZoomParallax (La Vida en Movimiento) 3",        src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776778049/mixboard-image_jp37sj.jpg",      description: "[URL_FOTO_YOSAI] Dynamic action shot of Yosai walking through a luxury black marble corridor, identical facial features from side profile, camera at waist height pointing upwards, wide-angle perspective, wearing high-end techwear with burgundy accents, neon burgundy (#82000f) linear lights reflecting on marble, motion blur on background elements, shot on Leica M11-P, 35mm Summilux lens, harsh cinematic flash mixed with ambient red light, grainy reportage style, sharp focus on the artist's face, 8k resolution --cref [URL_FOTO_YOSAI] --cw 100 --ar 16:9"},
    {id: 10,    image: "StorytellingSection (La Narrativa Íntima)",     src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776778207/mixboard-image_sikgqu.jpg",      description: "[URL_FOTO_YOSAI] Medium close-up of Yosai, perfect facial likeness preservation, sitting on a vintage leather stool in a dark high-end recording studio, mahogany wood panels in shadows, camera at eye level slightly offset to the right, thoughtful and soulful gaze directed away from lens, shot on ARRI Alexa 35, Panavision Primo Anamorphic 50mm, dramatic Chiaroscuro lighting, deep burgundy (#82000f) accent light on one side of the face, cinematic grain, volumetric dust motes in light beams, hyper-detailed textures of leather and skin --cref [URL_FOTO_YOSAI] --cw 100 --ar 4:5 --style raw"},
    {id: 11,    image: "StorytellingSection (La Narrativa Íntima) 2",   src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776778388/mixboard-image_5_rv9enh.png",    description: "- [URL_FOTO_YOSAI] Medium close-up of Yosai, perfect facial likeness preservation, sitting on a vintage leather stool in a dark high-end recording studio, mahogany wood panels in shadows, camera at eye level slightly offset to the right, thoughtful and soulful gaze directed away from lens, shot on ARRI Alexa 35, Panavision Primo Anamorphic 50mm, dramatic Chiaroscuro lighting, deep burgundy (#82000f) accent light on one side of the face, cinematic grain, volumetric dust motes in light beams, hyper-detailed textures of leather and skin --cref [URL_FOTO_YOSAI] --cw 100 --ar 4:5 --style raw"},
    {id: 12,    image: "MinimalistHero (El Statement Principal)",       src : "https://res.cloudinary.com/dlw6fupap/image/upload/q_auto/f_auto/v1776778724/mixboard-image_1_ccylr6.jpg",    description: "[URL_FOTO_YOSAI] Full vertical portrait, exact facial features of Yosai, standing in a high-end minimalist studio with charcoal black background, soft volumetric burgundy (#82000f) fog, wearing a premium wine-red velvet jacket with silk lapels, regal posture adjusting sleeves, camera placed at chest level, 15-degree low angle shot, shot on Fujifilm GFX 100II, GF 110mm f/2 lens, rim lighting in #82000f burgundy contouring shoulders and jawline, razor-sharp focus on eyes, hyper-realistic skin texture, 8k, high-end fashion editorial --cref [URL_FOTO_YOSAI] --cw 100 --ar 9:16 --v 6.0"},

]